Repository JoomGalleryfriends/JG4-dev, pull requests merged in 2023-03, with the labels that each got.

#74 Fix problems with image processor ImageMagick
  administrator/com_joomgallery/src/Service/IMGtools/IMtools.php
Labels: needs testing, GUI testing

#76 Fix error when memory_limit is set to -1
  administrator/com_joomgallery/src/Service/IMGtools/GDtools.php
Labels: needs testing, GUI testing

#70 Add support for webp images
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Service/IMGtools/GDtools.php
  administrator/com_joomgallery/src/Service/IMGtools/IMGtools.php
  administrator/com_joomgallery/src/Service/Uploader/HTMLUploader.php
  administrator/com_joomgallery/src/View/Image/RawView.php
Labels: needs testing, Linux testing done, GUI testing

#73 Messenger service
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/sql/uninstall.mysql.utf8.sql
  administrator/com_joomgallery/src/Extension/JoomgalleryComponent.php
  administrator/com_joomgallery/src/Extension/ServiceTrait.php
  administrator/com_joomgallery/src/Service/Messenger/MailMessenger.php
  administrator/com_joomgallery/src/Service/Messenger/Messenger.php
  administrator/com_joomgallery/src/Service/Messenger/MessengerInterface.php
  administrator/com_joomgallery/src/Service/Messenger/MessengerServiceInterface.php
  administrator/com_joomgallery/src/Service/Messenger/MessengerServiceTrait.php
  administrator/com_joomgallery/src/Service/Messenger/PmMessenger.php
  administrator/com_joomgallery/src/View/Faulties/HtmlView.php
  script.php
Labels: needs testing, DB changed, PHP testing

#81 Rename field 'created by' to 'owner'
  administrator/com_joomgallery/forms/category.xml
  administrator/com_joomgallery/forms/image.xml
Labels: Linux testing done, Windows testing done, GUI testing

#79 Tus upload service
  administrator/com_joomgallery/includes/tusspecs.php
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Controller/ImageController.php
  administrator/com_joomgallery/src/Controller/JoomAdminController.php
  administrator/com_joomgallery/src/Extension/JoomgalleryComponent.php
  administrator/com_joomgallery/src/Extension/ResponseTrait.php
  administrator/com_joomgallery/src/Service/TusServer/Exception/Abort.php
  administrator/com_joomgallery/src/Service/TusServer/Exception/BadHeader.php
  administrator/com_joomgallery/src/Service/TusServer/Exception/Curl.php
  administrator/com_joomgallery/src/Service/TusServer/Exception/File.php
  administrator/com_joomgallery/src/Service/TusServer/Exception/FileNotFoundException.php
  administrator/com_joomgallery/src/Service/TusServer/Exception/IOException.php
  administrator/com_joomgallery/src/Service/TusServer/Exception/IOExceptionInterface.php
  administrator/com_joomgallery/src/Service/TusServer/Exception/Max.php
  administrator/com_joomgallery/src/Service/TusServer/Exception/Request.php
  administrator/com_joomgallery/src/Service/TusServer/Exception/Required.php
  administrator/com_joomgallery/src/Service/TusServer/FileToolsService.php
  administrator/com_joomgallery/src/Service/TusServer/Server.php
  administrator/com_joomgallery/src/Service/TusServer/ServerInterface.php
  administrator/com_joomgallery/src/Service/TusServer/TusServiceInterface.php
  administrator/com_joomgallery/src/Service/TusServer/TusServiceTrait.php
  administrator/com_joomgallery/src/View/Image/HtmlView.php
  administrator/com_joomgallery/src/View/Images/HtmlView.php
  administrator/com_joomgallery/tmpl/image/edit.php
  administrator/com_joomgallery/tmpl/image/upload.php
  media/com_joomgallery/css/admin.css
Labels: needs testing, GUI testing

#84 Fix Save & New issue
  administrator/com_joomgallery/src/Table/CategoryTable.php
  administrator/com_joomgallery/src/Table/ConfigTable.php
  administrator/com_joomgallery/src/Table/ImageTable.php
  administrator/com_joomgallery/src/Table/TagTable.php
Labels: needs testing, GUI testing
