Repository JoomGalleryfriends/JG4-dev, pull requests merged in 2023-08, with the labels that each got.

#113 Access service v2
  administrator/com_joomgallery/access.xml
  administrator/com_joomgallery/forms/tag.xml
  administrator/com_joomgallery/includes/rules.php
  administrator/com_joomgallery/src/Extension/JoomgalleryComponent.php
  administrator/com_joomgallery/src/Helper/JoomHelper.php
  administrator/com_joomgallery/src/Service/Access/Access.php
  administrator/com_joomgallery/src/Service/Access/AccessInterface.php
  administrator/com_joomgallery/src/Service/Access/AccessServiceInterface.php
  administrator/com_joomgallery/src/Service/Access/AccessServiceTrait.php
  administrator/com_joomgallery/src/Service/Access/Base/AccessOwn.php
  administrator/com_joomgallery/src/Table/CategoryTable.php
  administrator/com_joomgallery/src/Table/ConfigTable.php
  administrator/com_joomgallery/src/Table/ImageTable.php
  administrator/com_joomgallery/src/Table/ImagetypeTable.php
  administrator/com_joomgallery/src/Table/TagTable.php
  administrator/com_joomgallery/src/View/Faulties/HtmlView.php
  administrator/com_joomgallery/tmpl/tag/edit.php
  script.php
Labels: DB changed, PHP testing

#114 Update from JG3
  administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
  administrator/com_joomgallery/sql/xml/mysql.xml
  joomgallery.xml
  script.php
Labels: needs testing, GUI testing

#116 Frontend: Starter-Kit
  administrator/com_joomgallery/src/Helper/JoomHelper.php
  administrator/com_joomgallery/src/Model/CategoriesModel.php
  administrator/com_joomgallery/src/Model/ConfigModel.php
  administrator/com_joomgallery/src/Model/TagsModel.php
  administrator/com_joomgallery/src/Service/Config/Config.php
  administrator/com_joomgallery/src/Service/Config/DefaultConfig.php
  administrator/com_joomgallery/src/Table/ImageTable.php
  media/com_joomgallery/css/site.css
  media/com_joomgallery/joomla.asset.json
  script.php
  site/com_joomgallery/forms/categoryform.xml
  site/com_joomgallery/forms/filter_images.xml
  site/com_joomgallery/forms/imageform.xml
  site/com_joomgallery/forms/subform_catparams.xml
  site/com_joomgallery/forms/subform_imageparams.xml
  site/com_joomgallery/language/en-GB/com_joomgallery.ini
  site/com_joomgallery/language/en-GB/com_joomgallery.jg3.ini
  site/com_joomgallery/language/en-GB/joomla.ini
  site/com_joomgallery/src/Model/CategoryformModel.php
  site/com_joomgallery/src/View/Categories/HtmlView.php
  site/com_joomgallery/src/View/Category/HtmlView.php
  site/com_joomgallery/src/View/Categoryform/HtmlView.php
  site/com_joomgallery/src/View/Image/RawView.php
  site/com_joomgallery/src/View/Images/HtmlView.php
  site/com_joomgallery/tmpl/categories/default.php
  site/com_joomgallery/tmpl/category/default.php
  site/com_joomgallery/tmpl/category/default.xml
  site/com_joomgallery/tmpl/categoryform/default.php
  site/com_joomgallery/tmpl/categoryform/default.xml
  site/com_joomgallery/tmpl/image/default.php
  site/com_joomgallery/tmpl/imageform/default.php
  site/com_joomgallery/tmpl/images/default.php
Labels: needs testing, GUI testing

#119 Fix mass upload with uppy
  administrator/com_joomgallery/src/Service/Uploader/UploaderServiceTrait.php
Labels: needs testing, GUI testing

#122 Fix for configuration check-in
  administrator/com_joomgallery/tmpl/configs/default.php
Labels: needs testing, GUI testing

#121 Use 'Admin approval' setting for uploads
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Table/ImageTable.php
Labels: needs testing, GUI testing

#129 Fix error during uninstallation v2
  script.php
Labels: bug, needs testing, GUI testing
