Repository JoomGalleryfriends/JG4-dev, pull requests merged in 2023-04, with the labels that each got.

#83 Overhaul of FileManager service
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/src/Controller/DisplayController.php
  administrator/com_joomgallery/src/Helper/JoomHelper.php
  administrator/com_joomgallery/src/Service/FileManager/FileManager.php
  administrator/com_joomgallery/src/Service/Filesystem/Filesystem.php
  administrator/com_joomgallery/src/Service/Filesystem/FilesystemInterface.php
  administrator/com_joomgallery/src/Service/Filesystem/FilesystemServiceInterface.php
  administrator/com_joomgallery/src/Service/Filesystem/FilesystemServiceTrait.php
  administrator/com_joomgallery/src/Service/Filesystem/LocalFilesystem.php
  administrator/com_joomgallery/src/Service/IMGtools/GDtools.php
  administrator/com_joomgallery/src/Service/IMGtools/IMGtoolsInterface.php
  administrator/com_joomgallery/src/Service/IMGtools/IMtools.php
  administrator/com_joomgallery/src/View/Faulties/HtmlView.php
  administrator/com_joomgallery/src/View/Image/RawView.php
  script.php
Labels: needs testing, DB changed, GUI testing, PHP testing

#86 Fix upload/filesystem issues
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/presets/content.xml
  administrator/com_joomgallery/services/provider.php
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/src/Extension/JoomgalleryComponent.php
  administrator/com_joomgallery/src/Extension/ServiceTrait.php
  administrator/com_joomgallery/src/Helper/JoomHelper.php
  administrator/com_joomgallery/src/Model/CategoryModel.php
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Service/Config/Config.php
  administrator/com_joomgallery/src/Service/Config/DefaultConfig.php
  administrator/com_joomgallery/src/Service/FileManager/FileManager.php
  administrator/com_joomgallery/src/Service/FileManager/FileManagerInterface.php
  administrator/com_joomgallery/src/Service/Filesystem/Filesystem.php
  administrator/com_joomgallery/src/Service/Filesystem/FilesystemInterface.php
  administrator/com_joomgallery/src/Service/IMGtools/GDtools.php
  administrator/com_joomgallery/src/Service/IMGtools/IMGtools.php
  administrator/com_joomgallery/src/Service/IMGtools/IMtools.php
  administrator/com_joomgallery/src/Service/Messenger/MailMessenger.php
  administrator/com_joomgallery/src/Service/Messenger/Messenger.php
  administrator/com_joomgallery/src/Service/Messenger/PmMessenger.php
  administrator/com_joomgallery/src/Service/Refresher/Refresher.php
  administrator/com_joomgallery/src/Service/Uploader/HTMLUploader.php
  administrator/com_joomgallery/src/Service/Uploader/Uploader.php
  administrator/com_joomgallery/src/Table/CategoryTable.php
  administrator/com_joomgallery/src/Table/ConfigTable.php
  administrator/com_joomgallery/src/View/Image/RawView.php
  joomgallery.xml
  script.php
Labels: needs testing, DB changed, GUI testing

#93 Changes layouts and adds character counter in edit forms
  administrator/com_joomgallery/forms/category.xml
  administrator/com_joomgallery/forms/image.xml
  administrator/com_joomgallery/forms/tag.xml
Labels: needs testing, GUI testing

#87 Solve visual problems in image manager
  administrator/com_joomgallery/forms/filter_images.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Field/UserdropdownField.php
Labels: needs testing, GUI testing
