Repository JoomGalleryfriends/JG4-dev, pull requests merged in 2024-05, with the labels that each got.

#211 Caching for config service
  administrator/com_joomgallery/src/Dispatcher/Dispatcher.php
  administrator/com_joomgallery/src/Field/ExternalconfigField.php
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Model/JoomAdminModel.php
  administrator/com_joomgallery/src/Service/Config/Config.php
  administrator/com_joomgallery/src/Service/Config/ConfigInterface.php
  administrator/com_joomgallery/src/Service/Config/ConfigServiceInterface.php
  administrator/com_joomgallery/src/Service/Config/ConfigServiceTrait.php
  administrator/com_joomgallery/src/Service/Config/DefaultConfig.php
  joomgallery.xml
  plugins/system/joomgallery/forms/form.xml
  plugins/system/joomgallery/joomgallery.xml
  plugins/system/joomgallery/language/en-GB/plg_system_joomgallery.ini
  plugins/system/joomgallery/language/en-GB/plg_system_joomgallery.sys.ini
  plugins/system/joomgallery/services/provider.php
  plugins/system/joomgallery/src/Extension/Joomgallery.php
Labels: needs testing, GUI testing, PHP testing

#214 Fix migration errors
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
  administrator/com_joomgallery/src/Model/MigrationModel.php
  administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.php
  administrator/com_joomgallery/tmpl/migration/step2.php
  media/com_joomgallery/js/migrator/dist/migrator.js
  media/com_joomgallery/js/migrator/dist/migrator.js.map
  media/com_joomgallery/js/migrator/src/index.js
Labels: DB changed, testing done

#218 Crop and metadata preparations from student
  administrator/com_joomgallery/forms/image.xml
  administrator/com_joomgallery/forms/subform_imageimgmetadata.xml
  administrator/com_joomgallery/forms/subform_imageinfocrop.xml
  administrator/com_joomgallery/forms/subform_metadata_iptc.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/language/en-GB/com_joomgallery.iptc.ini
  administrator/com_joomgallery/src/Controller/ImageController.php
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Service/IMGtools/IMGtools.php
  administrator/com_joomgallery/src/Service/MetaDataHandler/EXIFController.php
  administrator/com_joomgallery/src/Service/MetaDataHandler/IPTCController.php
  administrator/com_joomgallery/src/Service/MetaDataHandler/MetaData.php
  administrator/com_joomgallery/src/Service/MetaDataHandler/XMPController.php
  administrator/com_joomgallery/src/View/Image/HtmlView.php
  administrator/com_joomgallery/tmpl/image/crop.php
  administrator/com_joomgallery/tmpl/image/edit.php
  media/com_joomgallery/css/cropper.min.css
  media/com_joomgallery/joomla.asset.json
  media/com_joomgallery/js/cropper.min.js
Labels: needs discussion
