Repository JoomGalleryfriends/JG4-dev, pull requests merged in 2024-10, with the labels that each got.

#254 Add log entries
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Controller/CategoriesController.php
  administrator/com_joomgallery/src/Controller/ConfigController.php
  administrator/com_joomgallery/src/Controller/ConfigsController.php
  administrator/com_joomgallery/src/Controller/FaultiesController.php
  administrator/com_joomgallery/src/Controller/ImageController.php
  administrator/com_joomgallery/src/Controller/ImagesController.php
  administrator/com_joomgallery/src/Controller/MigrationController.php
  administrator/com_joomgallery/src/Controller/TagsController.php
  administrator/com_joomgallery/src/Field/ImgprocessorlistField.php
  administrator/com_joomgallery/src/Field/JgcategoryField.php
  administrator/com_joomgallery/src/Field/JgcategorydropdownField.php
  administrator/com_joomgallery/src/Field/JgimageField.php
  administrator/com_joomgallery/src/Helper/ConfigHelper.php
  administrator/com_joomgallery/src/Helper/JoomHelper.php
  administrator/com_joomgallery/src/Model/CategoryModel.php
  administrator/com_joomgallery/src/Model/ConfigModel.php
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Model/ImagetypeModel.php
  administrator/com_joomgallery/src/Model/JoomAdminModel.php
  administrator/com_joomgallery/src/Model/MigrationModel.php
  administrator/com_joomgallery/src/Model/TagModel.php
  administrator/com_joomgallery/src/Model/TagsModel.php
  administrator/com_joomgallery/src/Service/Access/Access.php
  administrator/com_joomgallery/src/Service/Config/Config.php
  administrator/com_joomgallery/src/Service/Config/DefaultConfig.php
  administrator/com_joomgallery/src/Service/FileManager/FileManager.php
  administrator/com_joomgallery/src/Service/Filesystem/Filesystem.php
  administrator/com_joomgallery/src/Service/IMGtools/GDtools.php
  administrator/com_joomgallery/src/Service/IMGtools/GifCreator.php
  administrator/com_joomgallery/src/Service/IMGtools/IMGtools.php
  administrator/com_joomgallery/src/Service/IMGtools/IMtools.php
  administrator/com_joomgallery/src/Service/Messenger/MailMessenger.php
  administrator/com_joomgallery/src/Service/Messenger/PmMessenger.php
  administrator/com_joomgallery/src/Service/Migration/Checks.php
  administrator/com_joomgallery/src/Service/Migration/Migration.php
  administrator/com_joomgallery/src/Service/Migration/MigrationServiceTrait.php
  administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.php
  administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.xml
  administrator/com_joomgallery/src/Service/Migration/Type.php
  administrator/com_joomgallery/src/Service/TusServer/FileToolsService.php
  administrator/com_joomgallery/src/Service/TusServer/Server.php
  administrator/com_joomgallery/src/Service/Uploader/HTMLUploader.php
  administrator/com_joomgallery/src/Service/Uploader/SingleUploader.php
  administrator/com_joomgallery/src/Service/Uploader/TUSUploader.php
  administrator/com_joomgallery/src/Service/Uploader/Uploader.php
  administrator/com_joomgallery/src/Table/CategoryTable.php
  administrator/com_joomgallery/src/Table/ImageTable.php
  administrator/com_joomgallery/src/View/Faulties/HtmlView.php
  administrator/com_joomgallery/src/View/Image/HtmlView.php
  script.php
Labels: testing done

#264 [Frontend] Category View: Fix issues
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
  administrator/com_joomgallery/src/Helper/JoomHelper.php
  administrator/com_joomgallery/src/Table/CategoryTable.php
  site/com_joomgallery/language/en-GB/com_joomgallery.ini
  site/com_joomgallery/src/Controller/CategoryController.php
  site/com_joomgallery/src/Model/CategoryModel.php
  site/com_joomgallery/src/View/Category/HtmlView.php
  site/com_joomgallery/tmpl/category/default.php
  site/com_joomgallery/tmpl/category/default.xml
  site/com_joomgallery/tmpl/category/default_cat.php
Labels: needs testing, DB changed, GUI testing, frontend

#261 Remove ACL for images
  administrator/com_joomgallery/access.xml
  administrator/com_joomgallery/forms/category.xml
  administrator/com_joomgallery/forms/image.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
  administrator/com_joomgallery/src/Controller/JoomFormController.php
  administrator/com_joomgallery/src/Field/JgcategorydropdownField.php
  administrator/com_joomgallery/src/Model/CategoryModel.php
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Model/JoomAdminModel.php
  administrator/com_joomgallery/src/Service/Access/Access.php
  administrator/com_joomgallery/src/Service/Access/AccessInterface.php
  administrator/com_joomgallery/src/Service/Access/Base/AccessOwn.php
  administrator/com_joomgallery/src/Table/CategoryTable.php
  administrator/com_joomgallery/src/Table/ImageTable.php
  administrator/com_joomgallery/src/Table/JoomTableTrait.php
  administrator/com_joomgallery/src/Table/MultipleAssetsTable.php
  administrator/com_joomgallery/src/Table/MultipleAssetsTableTrait.php
  administrator/com_joomgallery/src/User/User.php
  administrator/com_joomgallery/src/View/Categories/HtmlView.php
  administrator/com_joomgallery/src/View/Images/HtmlView.php
  administrator/com_joomgallery/tmpl/category/edit.php
  administrator/com_joomgallery/tmpl/image/edit.php
  administrator/com_joomgallery/tmpl/images/default.php
  plugins/system/joomowner/src/Extension/JoomgalleryOwner.php
  script.php
  site/com_joomgallery/src/Controller/CategoryController.php
  site/com_joomgallery/src/Controller/ImageController.php
  site/com_joomgallery/src/Controller/ImageformController.php
  site/com_joomgallery/tmpl/categories/default.php
  site/com_joomgallery/tmpl/category/default_cat.php
  site/com_joomgallery/tmpl/categoryform/default.php
  site/com_joomgallery/tmpl/image/default.php
  site/com_joomgallery/tmpl/imageform/default.php
  site/com_joomgallery/tmpl/images/default.php
Labels: needs testing, DB changed, GUI testing

#246 Dynamic processing of images in the frontend
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/forms/subform_imageconvert.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/layouts/joomla/form/field/subform/repeatable-config/sectionWithPopup.php
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
  administrator/com_joomgallery/src/Service/IMGtools/GDtools.php
  administrator/com_joomgallery/src/Service/IMGtools/IMGtools.php
  administrator/com_joomgallery/src/Service/IMGtools/IMGtoolsInterface.php
  administrator/com_joomgallery/src/Service/IMGtools/IMtools.php
  administrator/com_joomgallery/src/View/Image/RawView.php
  media/com_joomgallery/css/admin.css
  site/com_joomgallery/language/en-GB/com_joomgallery.ini
  site/com_joomgallery/src/View/Image/RawView.php
Labels: needs testing, DB changed, GUI testing

#271 Remove unfinished views from access
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/View/Faulties/HtmlView.php
  site/com_joomgallery/language/en-GB/com_joomgallery.ini
  site/com_joomgallery/src/View/Categoryform/HtmlView.php
  site/com_joomgallery/src/View/Imageform/HtmlView.php
Labels: needs testing, GUI testing

#273 Fix issue when replace image
  administrator/com_joomgallery/src/Controller/ImageController.php
Labels: needs testing, GUI testing

#276 Fix issues in ListAdminModel
  administrator/com_joomgallery/src/Model/JoomAdminModel.php
Labels: needs testing, GUI testing

#274 Change of the 'Image types' names
  administrator/com_joomgallery/src/Helper/JoomHelper.php
Labels: needs testing, GUI testing
