Repository JoomGalleryfriends/JG4-dev, pull requests merged in 2024-12, with the labels that each got.

#279 Add selection of the imagetype for the Lightbox
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
  administrator/com_joomgallery/src/Field/JgimagetypeField.php
  site/com_joomgallery/tmpl/category/default_cat.php
Labels: needs testing, DB changed, GUI testing, frontend

#293 Different issues during installation
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  script.php
Labels: needs testing, GUI testing

#292 Remove PHP warnings from plugins
  plugins/system/joomgallery/src/Extension/Joomgallery.php
  plugins/system/joomowner/src/Extension/JoomgalleryOwner.php
Labels: needs testing, GUI testing

#289 Fixes different upload issues
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Service/FileManager/FileManager.php
  administrator/com_joomgallery/src/Service/IMGtools/GDtools.php
  administrator/com_joomgallery/src/Service/IMGtools/GifCreator.php
  administrator/com_joomgallery/src/Service/IMGtools/IMGtools.php
  administrator/com_joomgallery/src/Service/IMGtools/IMtools.php
  administrator/com_joomgallery/src/Service/Uploader/Uploader.php
Labels: needs testing, GUI testing

#296 Change string to detect development version
  administrator/com_joomgallery/src/View/JoomGalleryView.php
Labels: needs testing, GUI testing

#287 Dynamic list of "Official JoomGallery extensions"
  administrator/com_joomgallery/includes/defines.php
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Helper/JoomHelper.php
  administrator/com_joomgallery/src/Model/ControlModel.php
  administrator/com_joomgallery/src/View/Control/HtmlView.php
  administrator/com_joomgallery/src/View/Migration/HtmlView.php
  administrator/com_joomgallery/tmpl/control/default.php
  joomgallery.xml
  plugins/privacy/joomgallery/joomgallery.xml
  plugins/system/joomgallery/joomgallery.xml
  plugins/system/joomowner/joomowner.xml
Labels: needs testing, GUI testing

#295 Access check for frontend views
  administrator/com_joomgallery/src/View/Image/RawView.php
  site/com_joomgallery/language/en-GB/com_joomgallery.ini
  site/com_joomgallery/src/Model/CategoryModel.php
  site/com_joomgallery/src/Model/ImageModel.php
  site/com_joomgallery/src/View/Category/HtmlView.php
  site/com_joomgallery/src/View/Category/JsonView.php
  site/com_joomgallery/src/View/Category/RawView.php
  site/com_joomgallery/src/View/Categoryform/HtmlView.php
  site/com_joomgallery/src/View/Image/HtmlView.php
  site/com_joomgallery/src/View/Image/JpgView.php
  site/com_joomgallery/src/View/Image/RawView.php
Labels: needs testing, GUI testing

#301 Fix issue with onMigrationBeforeSave event
  administrator/com_joomgallery/src/Model/MigrationModel.php
Labels: needs testing, GUI testing, backend

#308 Automatic image ordering
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Model/JoomAdminModel.php
  administrator/com_joomgallery/src/Table/ImageTable.php
  administrator/com_joomgallery/src/Table/JoomTableTrait.php
Labels: needs testing, GUI testing

#300 Layouts for Category view
  media/com_joomgallery/joomla.asset.json
  media/com_joomgallery/js/joomgrid.js
  site/com_joomgallery/layouts/joomgallery/grids/images.php
  site/com_joomgallery/layouts/joomgallery/grids/subcategories.php
  site/com_joomgallery/tmpl/category/default_cat.php
Labels: needs testing, GUI testing, frontend

#316 lenght > length
  administrator/com_joomgallery/src/Service/Access/Access.php
  administrator/com_joomgallery/src/Service/Migration/Migration.php
Labels: needs testing, GUI testing
