Repository JoomGalleryfriends/JG4-dev, pull requests merged in 2024-06, with the labels that each got.

#222 Fix error when exec is disabled
  administrator/com_joomgallery/src/Service/IMGtools/IMtools.php
Labels: testing done

#225 Add modalbox
  administrator/com_joomgallery/layouts/joomla/form/field/subform/repeatable-config/sectionWithPopup.php
  administrator/com_joomgallery/tmpl/config/edit.php
  administrator/com_joomgallery/tmpl/image/upload.php
Labels: needs testing, GUI testing

#230 Fix errors in system plugin
  plugins/system/joomgallery/src/Extension/Joomgallery.php
Labels: needs testing, GUI testing

#229 Fix error when reset config
  administrator/com_joomgallery/forms/config.xml
Labels: needs testing, GUI testing

#219 Update Error/Logging functionalities
  administrator/com_joomgallery/src/Extension/MessageTrait.php
Labels: needs testing, PHP testing

#224 Frontend cleanup and Infinte scroll
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/language/en-GB/com_joomgallery.sys.ini
  administrator/com_joomgallery/services/provider.php
  administrator/com_joomgallery/src/Helper/JoomHelper.php
  administrator/com_joomgallery/src/Model/ImagesModel.php
  administrator/com_joomgallery/src/Model/ImagetypesModel.php
  administrator/com_joomgallery/src/Model/JoomAdminModel.php
  administrator/com_joomgallery/src/Model/MigrationModel.php
  administrator/com_joomgallery/src/View/Faulties/HtmlView.php
  media/com_joomgallery/css/jg-icon-font.css
  media/com_joomgallery/css/site.css
  media/com_joomgallery/fonts/.DS_Store
  media/com_joomgallery/fonts/jg-icon-font.woff
  media/com_joomgallery/joomla.asset.json
  media/com_joomgallery/js/.DS_Store
  media/com_joomgallery/js/infinite-scroll.min.js
  site/com_joomgallery/forms/categoryform.xml
  site/com_joomgallery/forms/imageform.xml
  site/com_joomgallery/language/en-GB/com_joomgallery.ini
  site/com_joomgallery/src/Controller/CategoriesController.php
  site/com_joomgallery/src/Controller/CategoryController.php
  site/com_joomgallery/src/Controller/CategoryformController.php
  site/com_joomgallery/src/Controller/DisplayController.php
  site/com_joomgallery/src/Controller/ImageController.php
  site/com_joomgallery/src/Controller/ImageformController.php
  site/com_joomgallery/src/Controller/ImagesController.php
  site/com_joomgallery/src/Controller/JoomBaseController.php
  site/com_joomgallery/src/Controller/RoutingTrait.php
  site/com_joomgallery/src/Dispatcher/Dispatcher.php
  site/com_joomgallery/src/Model/CategoriesModel.php
  site/com_joomgallery/src/Model/CategoryModel.php
  site/com_joomgallery/src/Model/CategoryformModel.php
  site/com_joomgallery/src/Model/ImageModel.php
  site/com_joomgallery/src/Model/ImageformModel.php
  site/com_joomgallery/src/Model/ImagesModel.php
  site/com_joomgallery/src/Model/JoomItemModel.php
  site/com_joomgallery/src/Service/Router.php
  site/com_joomgallery/src/View/Categories/HtmlView.php
  site/com_joomgallery/src/View/Category/HtmlView.php
  site/com_joomgallery/src/View/Category/JsonView.php
  site/com_joomgallery/src/View/Categoryform/HtmlView.php
  site/com_joomgallery/src/View/Image/HtmlView.php
  site/com_joomgallery/src/View/Imageform/HtmlView.php
  site/com_joomgallery/src/View/Images/HtmlView.php
  site/com_joomgallery/src/View/JoomGalleryJsonView.php
  site/com_joomgallery/tmpl/.DS_Store
  site/com_joomgallery/tmpl/categories/default.php
  site/com_joomgallery/tmpl/categories/default.xml
  site/com_joomgallery/tmpl/categories/modal.php
  site/com_joomgallery/tmpl/category/default.php
  site/com_joomgallery/tmpl/category/default.xml
  site/com_joomgallery/tmpl/categoryform/default.php
  site/com_joomgallery/tmpl/categoryform/default.xml
  site/com_joomgallery/tmpl/image/default.php
  site/com_joomgallery/tmpl/image/default.xml
  site/com_joomgallery/tmpl/imageform/default.php
  site/com_joomgallery/tmpl/imageform/default.xml
  site/com_joomgallery/tmpl/images/default.php
  site/com_joomgallery/tmpl/images/default.xml
  site/com_joomgallery/tmpl/images/modal.php
Labels: needs testing, GUI testing

#235 Fix php error unexpected end of file
  administrator/com_joomgallery/services/provider.php
Labels: testing done

#238 Fix error in system plugin
  plugins/system/joomgallery/src/Extension/Joomgallery.php
Labels: needs testing, GUI testing

#239 Button visability in list views
  administrator/com_joomgallery/includes/rules.php
  administrator/com_joomgallery/src/Service/Access/Access.php
  administrator/com_joomgallery/src/View/Categories/HtmlView.php
  administrator/com_joomgallery/src/View/Configs/HtmlView.php
  administrator/com_joomgallery/src/View/Images/HtmlView.php
  administrator/com_joomgallery/src/View/Tags/HtmlView.php
  administrator/com_joomgallery/tmpl/categories/default.php
  administrator/com_joomgallery/tmpl/configs/default.php
  administrator/com_joomgallery/tmpl/images/default.php
  administrator/com_joomgallery/tmpl/tags/default.php
Labels: needs testing, GUI testing

#242 Simplifying usage of addLog()
  administrator/com_joomgallery/src/Extension/MessageTrait.php
  administrator/com_joomgallery/src/Model/CategoryModel.php
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Service/Messenger/MailMessenger.php
Labels: needs testing, PHP testing

#240 Category password field
  administrator/com_joomgallery/forms/category.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Model/CategoryModel.php
  administrator/com_joomgallery/src/Table/CategoryTable.php
  administrator/com_joomgallery/tmpl/category/edit.php
  media/com_joomgallery/css/admin.css
Labels: needs testing, GUI testing

#231 Choose different filesystem in categories
  administrator/com_joomgallery/forms/subform_catparams.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Field/JgdynamiclistField.php
  administrator/com_joomgallery/src/Field/JglistField.php
  administrator/com_joomgallery/src/Helper/ConfigHelper.php
  administrator/com_joomgallery/src/Helper/JoomHelper.php
  administrator/com_joomgallery/src/Model/CategoryModel.php
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Model/MigrationModel.php
  administrator/com_joomgallery/src/Service/Config/DefaultConfig.php
  administrator/com_joomgallery/src/Service/FileManager/FileManager.php
  administrator/com_joomgallery/src/Service/FileManager/FileManagerInterface.php
  administrator/com_joomgallery/src/Service/FileManager/FileManagerServiceInterface.php
  administrator/com_joomgallery/src/Service/FileManager/FileManagerServiceTrait.php
  administrator/com_joomgallery/src/Service/Migration/Migration.php
  administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.php
  administrator/com_joomgallery/src/Service/Uploader/SingleUploader.php
  administrator/com_joomgallery/src/Service/Uploader/Uploader.php
  administrator/com_joomgallery/src/Table/CategoryTable.php
Labels: needs testing, GUI testing
