Repository JoomGalleryfriends/JG4-dev, pull requests merged in 2025-01, with the labels that each got.

#318 Fix issues in multiple uploader
  administrator/com_joomgallery/src/Service/Uploader/Uploader.php
  media/com_joomgallery/js/uppy/dist/uppy-uploader.js
  media/com_joomgallery/js/uppy/dist/uppy-uploader.js.map
  media/com_joomgallery/js/uppy/package-lock.json
  media/com_joomgallery/js/uppy/package.json
  media/com_joomgallery/js/uppy/src/index.js
  media/com_joomgallery/js/uppy/src/jgDashboard/components/FileItem/FileInfo/index.js
  media/com_joomgallery/js/uppy/src/jgprocessor.js
Labels: needs testing, GUI testing

#324 Fix issue with category list filter
  administrator/com_joomgallery/src/Model/CategoriesModel.php
Labels: needs testing, GUI testing

#333 lightbox improvement & new param
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
  media/com_joomgallery/js/joomgrid.js
  site/com_joomgallery/tmpl/category/default_cat.php
Labels: DB changed, frontend

#340 Change language string
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
Labels: GUI testing, backend

#334 Tags & Fields for Simgle Image View
  administrator/com_joomgallery/src/Model/JoomAdminModel.php
  administrator/com_joomgallery/src/Service/Access/Access.php
  administrator/com_joomgallery/src/Service/Access/AccessInterface.php
  administrator/com_joomgallery/src/Service/Access/Base/AccessOwn.php
  media/com_joomgallery/css/site.css
  site/com_joomgallery/layouts/joomgallery/content/metadata.php
  site/com_joomgallery/layouts/joomgallery/content/tags.php
  site/com_joomgallery/src/Model/ImageModel.php
  site/com_joomgallery/tmpl/image/default.php
Labels: needs testing, GUI testing, frontend

#339 Fix issues with JgTagField
  administrator/com_joomgallery/src/Controller/JoomAdminController.php
  administrator/com_joomgallery/src/Controller/JoomFormController.php
  administrator/com_joomgallery/src/Controller/TagsController.php
  administrator/com_joomgallery/src/Extension/MessageTrait.php
  administrator/com_joomgallery/src/Field/JgtagField.php
  administrator/com_joomgallery/src/Model/TagsModel.php
  administrator/com_joomgallery/src/Table/ImageTable.php
Labels: needs testing, GUI testing

#346 Add link to category overview
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
  site/com_joomgallery/language/en-GB/com_joomgallery.ini
  site/com_joomgallery/tmpl/category/default_cat.php
  site/com_joomgallery/tmpl/gallery/default.php
Labels: DB changed, GUI testing, frontend

#311 Fix issues with DPMedia (filesystem plugins)
  administrator/com_joomgallery/forms/image.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
  administrator/com_joomgallery/src/Helper/FilesystemHelper.php
  administrator/com_joomgallery/src/Helper/JoomHelper.php
  administrator/com_joomgallery/src/Model/CategoryModel.php
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Service/FileManager/FileManager.php
  administrator/com_joomgallery/src/Service/FileManager/FileManagerInterface.php
  administrator/com_joomgallery/src/Service/Filesystem/Exception/AdapterNotFoundException.php
  administrator/com_joomgallery/src/Service/Filesystem/Filesystem.php
  administrator/com_joomgallery/src/Service/Uploader/Uploader.php
  administrator/com_joomgallery/src/View/Image/RawView.php
  administrator/com_joomgallery/src/View/Images/HtmlView.php
  administrator/com_joomgallery/tmpl/image/edit.php
  site/com_joomgallery/tmpl/images/default.php
Labels: needs testing, DB changed, GUI testing

#343 [Image save] Change files in filesystem before store to DB
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Model/CategoryModel.php
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Service/FileManager/FileManager.php
Labels: needs testing, GUI testing

#349 Imporve error logging during migration
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Model/MigrationModel.php
  administrator/com_joomgallery/src/Service/FileManager/FileManager.php
  administrator/com_joomgallery/src/Service/FileManager/FileManagerInterface.php
  administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.php
Labels: needs testing, GUI testing

#350 Add language constants
  site/com_joomgallery/language/en-GB/com_joomgallery.ini
  site/com_joomgallery/tmpl/category/default_cat.php
  site/com_joomgallery/tmpl/gallery/default.php
  site/com_joomgallery/tmpl/image/default.php
Labels: frontend

#351 Fix: Move image to another filesystem
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/View/Category/HtmlView.php
  administrator/com_joomgallery/tmpl/category/edit.php
Labels: needs testing, GUI testing

#354 Fix random image error
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
  site/com_joomgallery/layouts/joomgallery/grids/subcategories.php
Labels: needs testing, DB changed, GUI testing, frontend
