Repository JoomGalleryfriends/JG4-dev, pull requests merged in 2025-02, with the labels that each got.

#362 Fix wrong default value
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
Labels: needs testing, DB changed, frontend

#363 Sorting images category & gallery view
  site/com_joomgallery/src/Model/CategoryModel.php
  site/com_joomgallery/src/Model/GalleryModel.php
Labels: needs testing, GUI testing, frontend

#358 Fix two frontend PHP errors
  site/com_joomgallery/layouts/joomgallery/content/metadata.php
  site/com_joomgallery/src/Model/CategoryModel.php
  site/com_joomgallery/src/Model/GalleryModel.php
Labels: needs testing, GUI testing, frontend

#357 Default pagination for subcategories
  administrator/com_joomgallery/forms/config.xml
  site/com_joomgallery/src/Model/CategoryModel.php
  site/com_joomgallery/src/View/Category/HtmlView.php
  site/com_joomgallery/tmpl/category/default.xml
  site/com_joomgallery/tmpl/category/default_cat.php
Labels: needs testing, GUI testing, frontend

#366 Bug fix for justified layout
  media/com_joomgallery/css/site.css
  media/com_joomgallery/js/joomgrid.js
Labels: needs testing, GUI testing, frontend

#370 Fix issue when loading multiple items
  site/com_joomgallery/src/Model/CategoryModel.php
  site/com_joomgallery/src/Model/ImageModel.php
Labels: needs testing, GUI testing

#367 Add deleteSource() method to Migration script
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Controller/JoomAdminController.php
  administrator/com_joomgallery/src/Controller/JoomFormController.php
  administrator/com_joomgallery/src/Controller/MigrationController.php
  administrator/com_joomgallery/src/Extension/MessageTrait.php
  administrator/com_joomgallery/src/Service/Migration/Migration.php
  administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.php
Labels: needs testing, GUI testing

#371 fix javascript errors [imgJust]
  media/com_joomgallery/js/joomgrid.js
Labels: needs testing, GUI testing

#372 Add test view in the backend
  administrator/com_joomgallery/src/View/Test/HtmlView.php
Labels: needs testing, PHP testing, backend

#373 Fix issue with xml path
  administrator/com_joomgallery/src/Field/ExternalconfigField.php
Labels: needs testing, GUI testing

#375 Lightgallery image description
  media/com_joomgallery/css/site.css
  site/com_joomgallery/layouts/joomgallery/grids/images.php
Labels: needs testing, GUI testing

#379 Fix issue with asset_id during migration
  administrator/com_joomgallery/src/Service/Migration/Migration.php
  administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.php
Labels: needs testing, GUI testing

#384 Add language filter
  administrator/com_joomgallery/forms/filter_categories.xml
  administrator/com_joomgallery/forms/filter_images.xml
  administrator/com_joomgallery/forms/filter_tags.xml
  administrator/com_joomgallery/src/Model/CategoriesModel.php
  administrator/com_joomgallery/src/Model/ImagesModel.php
Labels: needs testing, GUI testing, backend
